### ISSUE TITLE
Currently not able to generate updated lists

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-web-repo#39]
Some is off with the service somehow. Currently in the logs:

```
Tue May 23 00:00:01 2017: manjaro-web-repo is starting
Tue May 23 00:01:18 2017: http://jaran.undip.ac.id/manjaro/: can't read state file
Tue May 23 00:02:41 2017: 79 mirror(s) added
Tue May 23 00:02:41 2017: JSON output generated
Tue May 23 00:02:41 2017: HTML output generated
Tue May 23 00:02:41 2017: manjaro-web-repo is stopping
Tue May 23 00:20:01 2017: manjaro-web-repo is starting
Tue May 23 00:40:01 2017: manjaro-web-repo is starting
...
Fri May 26 10:40:01 2017: manjaro-web-repo is starting
Fri May 26 11:00:01 2017: manjaro-web-repo is starting
Fri May 26 11:20:01 2017: manjaro-web-repo is starting
Fri May 26 11:40:01 2017: manjaro-web-repo is starting
```

**Comment by philmmanjaro** [comment]
Seems that is the actual error:

```
python3 /var/www/manjaro-web-repo/src/main.py &
[1] 23459
root@Debian:/var/www/manjaro-web-repo# Manjaro-web-repo is starting
Traceback (most recent call last):
  File "/var/www/manjaro-web-repo/src/main.py", line 68, in <module>
    status_checker.get_mirrors()
  File "/var/www/manjaro-web-repo/src/main.py", line 30, in get_mirrors
    object_pairs_hook=OrderedDict)
  File "/usr/lib/python3.2/json/__init__.py", line 322, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.2/json/decoder.py", line 353, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.2/json/decoder.py", line 369, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 401 column 13 (char 8670)

[1]+  Exit 1                  python3 /var/www/manjaro-web-repo/src/main.py
```
